export const EMPLOYEE_LOGIN_REQUEST = 'EMPLOYEE_LOGIN_REQUEST';
export const EMPLOYEE_LOGIN_SUCCESS = 'EMPLOYEE_LOGIN_SUCCESS';
export const EMPLOYEE_LOGIN_FAIL = 'EMPLOYEE_LOGIN_FAIL';
export const EMPLOYEE_LOGOUT = 'EMPLOYEE_LOGOUT';

export const EMPLOYEE_REGISTER_REQUEST = 'EMPLOYEE_REGISTER_REQUEST';
export const EMPLOYEE_REGISTER_SUCCESS = 'EMPLOYEE_REGISTER_SUCCESS';
export const EMPLOYEE_REGISTER_FAIL = 'EMPLOYEE_REGISTER_FAIL';

export const EMPLOYEE_DETAILS_REQUEST = 'EMPLOYEE_DETAILS_REQUEST';
export const EMPLOYEE_DETAILS_SUCCESS = 'EMPLOYEE_DETAILS_SUCCESS';
export const EMPLOYEE_DETAILS_FAIL = 'EMPLOYEE_DETAILS_FAIL';

export const EMPLOYEE_UPDATE_PROFILE_REQUEST =
  'EMPLOYEE_UPDATE_PROFILE_REQUEST';
export const EMPLOYEE_UPDATE_PROFILE_SUCCESS =
  'EMPLOYEE_UPDATE_PROFILE_SUCCESS';
export const EMPLOYEE_UPDATE_PROFILE_FAIL = 'EMPLOYEE_UPDATE_PROFILE_FAIL';
export const EMPLOYEE_UPDATE_PROFILE_RESET = 'EMPLOYEE_UPDATE_PROFILE_RESET';

export const EMPLOYEE_LIST_REQUEST = 'EMPLOYEE_LIST_REQUEST';
export const EMPLOYEE_LIST_SUCCESS = 'EMPLOYEE_LIST_SUCCESS';
export const EMPLOYEE_LIST_FAIL = 'EMPLOYEE_LIST_FAIL';
export const EMPLOYEE_LIST_RESET = 'EMPLOYEE_LIST_RESET';

export const EMPLOYEE_DELETE_REQUEST = 'EMPLOYEE_DELETE_REQUEST';
export const EMPLOYEE_DELETE_SUCCESS = 'EMPLOYEE_DELETE_SUCCESS';
export const EMPLOYEE_DELETE_FAIL = 'EMPLOYEE_LIST_FAIL';

export const EMPLOYEE_UPDATE_REQUEST = 'EMPLOYEE_UPDATE_REQUEST';
export const EMPLOYEE_UPDATE_SUCCESS = 'EMPLOYEE_UPDATE_SUCCESS';
export const EMPLOYEE_UPDATE_FAIL = 'EMPLOYEE_UPDATE_FAIL';
export const EMPLOYEE_UPDATE_RESET = 'EMPLOYEE_UPDATE_RESET';
